### ISSUE TITLE
Limit cell types in spillover step of xCell

### ISSUE THREAD

**Issue by grst** [grst/immunedeconv#1]
According to @dviraran, the performance of xCell can be improved 
by limiting the cell types to immune cells only in the spillover step. 

See also [this tutorial](http://comphealth.ucsf.edu/sample-apps/xCellView/xCell-Immport.html). 

As this package targets *immune* cells, it probably makes sense to limit the cell types per default in the 
`deconvolute` function.

**Comment by dviraran** [comment]
Thanks Gregor. 
Just to be clear - "limiting the cell types to immune cells" should be "limiting the cell types to cell types of interest". For example, If you are running it for PBMC and no macrophages are expected, its better to run xCell without them.

**Comment by grst** [comment]
ok, I see. 

1) Would it already help to limit the analysis to immune cells, as a default option for the 'naive user'?

2) For the benchmark, I would consider it as 'fair' to limit xCell to the same cell types that the other methods are using. What do you think? 

3) I am thinking of how to make this accessible to users. Maybe a `use_cell_types` argument of the `deconvolute()` function. Maybe you could also implement this on the xCell side as a parameter to the `xCellAnalysis` function that would wrap the code you show in the tutorial.

**Comment by dviraran** [comment]
1. No, because there is almost no spillover between the immune and the other cell types.

2. Yes. In my experiments, this can significantly improve results for some cell types

3. Thanks for the suggestion. I added cell.types.use argument to the xCellAnalysis function.

**Comment by grst** [comment]
Great! I'll look into this next week.

**Comment by grst** [comment]
@dviraran, I now implemented a `expected_cell_types` parameter for the `deconvolute` function in the feature/expected_cell_types branch. 

At the same time I constrained xCell to the following cell types in the [benchmark pipeline](https://github.com/grst/immune_deconvolution_benchmark). 

See the config file for the exact cell types. 
https://github.com/grst/immune_deconvolution_benchmark/blob/836b8a631741fb63f3f547ec4a05c7f700e1a9f9/notebooks/config.R#L48

What do you think? 

The results did not change a lot. NK cells improved quite a bit, though.
This is what the figures from the manuscript would look like with the modification: 

![summary](https://user-images.githubusercontent.com/7051479/48766844-a36f0d80-ecb5-11e8-90b7-c69e1a926e7d.png)
![detection_limit_fp](https://user-images.githubusercontent.com/7051479/48766841-a36f0d80-ecb5-11e8-8c76-1289bf7acf97.png)
![spillover_migration_chart](https://user-images.githubusercontent.com/7051479/48766843-a36f0d80-ecb5-11e8-850b-d0e596bc50c6.png)

**Comment by dviraran** [comment]
Thanks. Looks good to me. 
The only reason it bothered me is the apparent failure of xCell in monocytes in the FACS validation (1c,d). I think that it is overcompensating with macrophages, and therefore the correlations look bad. Now its better... 
Not sure what is the problem with NK cells.

Best,
Dvir

**Comment by grst** [comment]
Great, will update the preprint shortly!
