### ISSUE TITLE
tibble version conflict

### ISSUE THREAD

**Issue by grst** [grst/immunedeconv#10]
Reported by @eirikhoye via Email. 

I tried installing following your installation instruction, using conda 4.6.14:

Setting up a conda environment using the commands:
$ conda create -n deconvolution
$ conda activate deconvolution
And installing the immunedeconv package:
$ conda install -c grst -c bioconda -c conda-forge r-immunedeconv
The conda install appear to run successfully, however when i open an R terminal and load the immunedeconv package, I get the error:

> library(deconvolution)
Loading required package: EPIC
Error: package or namespace load failed for ‘immunedeconv’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
namespace ‘tibble’ 1.3.3 is being loaded, but >= 1.4.2 is required

It looks like the deconvolution package requires tibble version >= 1.4.2, however when I try to update the tibble package using conda, conda will uninstall the deconvolution package:

$ conda install -c bioconda r-tibble=2.1.1
...
The following packages will be REMOVED:

  r-immunedeconv-1.1.0-r341_0
  r-xcell-1.12-r341_0
...

**Comment by grst** [comment]
Hi @eirikhoye, 

the problem appears to be due to a recent conda compiler update (see https://github.com/conda/conda/issues/8413). 

Quick fix: use the `cf201901` label for the conda-forge channel. 
`conda install -c grst -c bioconda -c conda-forge/label/cf201901 r-immunedeconv`

Can you tell me if that works for you? 

On the long run, I should probably update the entire package to work with R `3.5.1`. 

Best, 
Gregor

**Comment by eirikhoye** [comment]
Excellent! I managed to get the immunedeconv to work now, running a simple test sample matrix, and outputting quanTIseq immune cell fractions. Thank you so much, this package should make my project a lot easier to do.

Regards, 
Eirik
