### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by ectopicaPKC** [grst/immunedeconv#13]
devtools::install_github('grst/immunedeconv')
Downloading GitHub repo grst/immunedeconv@master
Error in read.dcf(path) : 
  Found continuation line starting '  "Julien Racle <jul ...' at begin of record.

When I run the above for installation through R this is the error I get. 

Thanks in advance for your help.

**Comment by grst** [comment]
Hi @ectopicaPKC, 

I fixed some dependency and Bioconductor issues in the [latest release](https://github.com/grst/immunedeconv/releases/tag/v1.1.1). 
Can you try again using the latest version?
