### ISSUE TITLE
error when running xcell

### ISSUE THREAD

**Issue by trptyrphe11** [grst/immunedeconv#18]
Input is count matrix of RNAseq;
command: res = deconvolute(exprM, "xcell")
>>> Running xcell
Error in xCell::xCellAnalysis(gene_expression_matrix, rnaseq = rnaseq,  :
  unused arguments (cell.types.use = cell_types_xcell, parallel.sz = config_env$xcell_cores)

**Comment by grst** [comment]
This sounds like a problem with xcell. If other methods work well, you
should file a bug in the xcell repository (dviraran/xcell).

Beware that most methods expect normalized counts (shouldn't matter for
xcell, though).
If you file a bug, make sure to include a [minimal working example](
https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example)
to reproduce the problem.

Cheers,
Gregor

**Comment by trptyrphe11** [comment]
Thanks, actually your comment leads to my second question: would it be possible that add expected data type for each method in the document (for example, count vs normalized (or more specifically tpm/fpkm/etc.)? Thanks.

**Comment by grst** [comment]
That's a good point.
I'll update the documentation and keep this open until then.

**Comment by grst** [comment]
Close #18 per #19.
