### ISSUE TITLE
Better example dataset

### ISSUE THREAD

**Issue by grst** [grst/immunedeconv#20]
The current example dataset included in immunedeconv is based on facs-purified bulk samples containing a single cell type only. This is not very well suited to demonstrate the methods. 

@jracle85, would you be ok with me including the four samples from the EPIC paper (LAU125, LAU355, etc.)?

**Comment by jracle85** [comment]
Hi @grst,

Thanks for asking. Sure, you could use this dataset as an example. But please cite our work as the source of the data.

Cheers,

Julien
