### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by zhaoliang0302** [grst/immunedeconv#21]
Hi, I install this package: 
` remotes::install_github("grst/immunedeconv")`
it shows:
```
Downloading GitHub repo grst/immunedeconv@master
Error: Failed to install 'immunedeconv' from GitHub:
  invalid multibyte string, element 1
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
```

```
platform: Win8.1 x64
R v3.6.0
remotes v2.1.0
```

**Comment by grst** [comment]
Hmmm... I can't reproduce the error. On the [CI it builds fine on Windows with R3.6.1](https://ci.appveyor.com/project/grst/immunedeconv). To me, it sounds a bit as if the file you downloaded was corrupted. 

You could try to 
* simply try again. If that does not work, 
* download the tar.gz file manually (https://github.com/grst/immunedeconv/archive/master.tar.gz).
* and then use, for instance, `devtools::install_local('tarfile.tar.gz')` to install the package.

**Comment by zhaoliang0302** [comment]
I tried to upgrade R to 3.6.1 and it still failed, but I tried `Sys.setlocale(category = "LC_ALL", locale = "us") `before calling the install function, it works

**Comment by grst** [comment]
Thanks for the update... glad you figured out a way around!
