### ISSUE TITLE
CIBERSORT error and strange results

### ISSUE THREAD

**Issue by ahwanpandey** [grst/immunedeconv#23]
Hi @grst,

I tried running the following code and got this error:

```
> res_cibersort = deconvolute(dataset_racle$expr_mat, "cibersort")

>>> Running cibersort
assertion failed: CIBERSORT.R is provided
Error: exists("cibersort_binary", envir = config_env) is not TRUE
```

But if I define the CIBERSORT.R script and the signature matrix, the function runs fine, but the output looks weird/truncated

```
cibersort_binary = "/path/to/CIBERSORT.R"
cibersort_mat = "/path/to/LM22.txt"

> res_cibersort = deconvolute(dataset_racle$expr_mat, "cibersort")

>>> Running cibersort
> res_cibersort 
# A tibble: 3 x 5
  cell_type   LAU125 LAU355 LAU1255 LAU1314
  <chr>        <dbl>  <dbl>   <dbl>   <dbl>
1 Monocyte   0.0607  0.0652 0.0895        0
2 Eosinophil 0.00293 0      0.0123        0
3 Neutrophil 0       0      0.00687       0
```

Do you have any suggestions on what might be causing this?

Thanks!

**Comment by ahwanpandey** [comment]
Ah nevermind! I found the detailed documentation with specific steps for the CIBERSORT:

https://grst.github.io/immunedeconv/articles/immunedeconv.html

Thanks.

**Comment by grst** [comment]
glad it worked!

Cheers,
G

**Comment by jianguozhouzunyimedicaluniversity** [comment]
thanks, but when I run this get errors. @grst @ahwanpandey 
>>> Running cibersort_abs
Error: C stack usage  7970176 is too close to the limit

**Comment by grst** [comment]
That sounds like a problem with CIBERSORT itself and you should report it to the CIBERSORT authors. 
Also, check https://stackoverflow.com/questions/14719349/error-c-stack-usage-is-too-close-to-the-limit.

**Comment by jianguozhouzunyimedicaluniversity** [comment]
> That sounds like a problem with CIBERSORT itself and you should report it to the CIBERSORT authors.
> Also, check https://stackoverflow.com/questions/14719349/error-c-stack-usage-is-too-close-to-the-limit.

thanks.

**Comment by BenjaminDEMAILLE** [comment]
> Hi @grst,
> 
> I tried running the following code and got this error:
> 
> ```
> > res_cibersort = deconvolute(dataset_racle$expr_mat, "cibersort")
> 
> >>> Running cibersort
> assertion failed: CIBERSORT.R is provided
> Error: exists("cibersort_binary", envir = config_env) is not TRUE
> ```
> 
> But if I define the CIBERSORT.R script and the signature matrix, the function runs fine, but the output looks weird/truncated
> 
> ```
> cibersort_binary = "/path/to/CIBERSORT.R"
> cibersort_mat = "/path/to/LM22.txt"
> 
> > res_cibersort = deconvolute(dataset_racle$expr_mat, "cibersort")
> 
> >>> Running cibersort
> > res_cibersort 
> # A tibble: 3 x 5
>   cell_type   LAU125 LAU355 LAU1255 LAU1314
>   <chr>        <dbl>  <dbl>   <dbl>   <dbl>
> 1 Monocyte   0.0607  0.0652 0.0895        0
> 2 Eosinophil 0.00293 0      0.0123        0
> 3 Neutrophil 0       0      0.00687       0
> ```
> 
> Do you have any suggestions on what might be causing this?
> 
> Thanks!

where didi you find those files ?

**Comment by naiem836** [comment]
# Set the path to the CIBERSORT binary
>  set_cibersort_binary("D:/SingleCellDataAn/dd/finaldd/FurtherAnalysis/3.GSVA/CIBERSORT.R")
>  # Set the path to the LM22 gene signature file
>  set_cibersort_mat("D:/SingleCellDataAn/dd/finaldd/FurtherAnalysis/3.GSVA/LM22.txt")
>  DDLGG_CM_cibersort_abs<- immunedeconv::deconvolute( DDLGG_CM, array = TRUE, tumor = TRUE, method = "cibersort_abs")

>>> Running cibersort_abs
Error in if (dups > 0) { : argument is of length zero

can anyone help me, I got bogged down here.

**Comment by single0202** [comment]
@naiem836 
hi, I got the same error. I found it is because of the CIBERSORT.R.  Check the CIBERSORT function in CIBERSORT.R.  The argument of sig_matrix and mixture_file need file path but v1.04 need two matix. 
Change the code line 129 -144 to like the follows

`CIBERSORT <- function(sig_matrix, mixture_file, perm=0, QN=TRUE, absolute=FALSE, abs_method='sig.score'){
    
    if(absolute && abs_method != 'no.sumto1' && abs_method != 'sig.score') stop("abs_method must be set to either 'sig.score' or 'no.sumto1'")
    
    #read in data
    X <- read.table(sig_matrix,header=T,sep="\t",row.names=1,check.names=F)
#    X <- sig_matrix
#    Y <- mixture_file
    Y <- read.table(mixture_file, header=T, sep="\t",check.names=F)
    #to prevent crashing on duplicated gene symbols, add unique numbers to identical names
    dups <- dim(Y)[1] - length(unique(rownames(Y)))
    if(dups > 0) {
        warning(paste(dups," duplicated gene symbol(s) found in mixture file!",sep=""))
        rownames(Y) <- make.names(rownames(Y), unique=TRUE)
    }else {rownames(Y) <- Y[,1]}
    Y <- Y[,-1]`
