### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by liqilong111** [grst/immunedeconv#5]
**problem**：Installation failed: SVN does not seem to be installed on your system.
Please tell me how to solve this problem！thank you！

**Comment by grst** [comment]
Hi @liqilong111, 

thanks for reporting your issue. I assume that you are referring to 
the ["Standard R package"](https://github.com/grst/immunedeconv#standard-r-package) installation instructions.  To solve the problem, please provide further information:

* Are you working on Windows, mac or linux? 
* Are you using Rstudio?
* Try to install the dependency packages one-by-one to track down which one causes the error.
