### ISSUE TITLE
i am not able to install  immunedeconv and snakemake with conda 

### ISSUE THREAD

**Issue by deo999** [grst/immunedeconv#7]
hello,
you have mention conda as prefer installation but itz not working i am using centos7

conda install -c grst,bioconda,conda-forge r-immunedeconv
Solving environment: failed

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/grst,bioconda,conda-forge/noarch/repodata.json>
Elapsed: 00:05.772163
CF-RAY: 4ac0e33eba7d8a79-BOM

The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/grst,bioconda,conda-forge

As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
empty. please request that the channel administrator create
`noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state.
Further configuration help can be found at <https://conda.io/docs/config.html>

**Comment by grst** [comment]
Hi @deo999, 

thanks for reporting!
The comma-notation for channels does not work, the correct command is: 
```
conda install -c grst -c bioconda -c conda-forge r-immunedeconv
```

I fixed the documentation in [08333d7](https://github.com/grst/immunedeconv/commit/08333d7c0a87abc31e5d1da23a47556c0bb12cab). 

Does this work for you? Let me know if you have any further problems! 

Gregor

**Comment by deo999** [comment]
hey i tried this one also this is also  not working.
conda install -c grst -c bioconda -c conda-forge r-immunedeconv
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:


  - r-immunedeconv

Current channels:

  - https://conda.anaconda.org/grst/win-64
  - https://conda.anaconda.org/grst/noarch
  - https://conda.anaconda.org/bioconda/win-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64

**Comment by deo999** [comment]
i want to use it please fix it.

**Comment by grst** [comment]
Atm, windows is not supported for installation via conda. The problem is
that some dependencies are not available on conda for windows.

You could try the manual istallation or give linux a shot.

**Comment by deo999** [comment]
Yes it working on Linux but how to run immunodonv after installing with
conda

**Comment by grst** [comment]
Please refer to the documentation:
https://grst.github.io/immunedeconv/articles/immunedeconv.html

If you have any more specific questions, let me know.
